#!/bin/sh


IP=192.168.1.171

set -x

wget -O search.log --no-http-keep-alive "http://$IP/cgi-bin/api.cgi?cmd=Search&rs=484548&user=admin&password=lucky123"

cat search.log

wget -O snap.jpg --no-http-keep-alive "http://$IP/cgi-bin/api.cgi?cmd=Snap&channel=0&rs=484548&user=admin&password=lucky123"

file snap.jpg