#!/bin/sh

BUILD=./build

# rm -rf $BUILD

if [ ! -d $BUILD ] ; then
    cmake -B $BUILD .
fi

clear
cmake --build $BUILD --parallel=2
rc=$?

if [ $rc -ne 0 ] ; then
    exit 1;
fi

date
set-title home_security: build complete
countdown 30
